### ISSUE TITLE
Pictures to Hashcode

### ISSUE THREAD

**Issue by Itsredd** [Itsredd/theMillionDollarProject#2]
Damit wir Bilder sinnvoll überprüfen können, brauchen wir eine Möglichkeit wie man einen ähnlichen Hashcode bekommt bei ähnlichen Bildern.

**Comment by xela1601** [comment]
Habe das pyhton-skript hochgeladen. Der Vergleich der erzeugten Hashes am Beispiel der "one does not simply"-memes zeigt aber, dass dies kein gutes Verfahren ist, da die hashes schon ziemlich verschieden sind, wenn die Bilder etwas anders zugeschnitten sind und Schriftzüge im Bild vorhanden sind.
