### ISSUE TITLE
Develop Toolchain

### ISSUE THREAD

**Issue by Itsredd** [Itsredd/theMillionDollarProject#4]
Welche IDE?
Welche Programmiersprache?
Welche Packages brauchen wir?
Brauchen wir Hardware?

**Comment by Itsredd** [comment]
[https://dt-cdn.net/images/atlassian-tools-588-0ab53fd0c4.png](Toolchain modell)
Preise sind in der Excel Tabelle
[Toolchain_preise.xlsx](https://github.com/Itsredd/theMillionDollarProject/files/3072462/Toolchain_preise.xlsx)

**Comment by Itsredd** [comment]
Pycharm IDE:
Preise: Nutzer/Jahr
€199.00 im ersten Jahr
€159.00 im zweiten Jahr
€119.00 im dritten Jahr

Programmiersprache ist Python. Mit evtl kleinen ausfällen in C, C++, C# basieren auf verschiedenen Problemen in der Bild Analyse.

Packages:
Pillow: https://pillow.readthedocs.io/en/stable/
Pandas: https://pandas.pydata.org/
Scrapy: https://scrapy.org/
Packages sind unter: File -> Settings -> Project -> Project Interpreter -> +
zu installieren!

**Comment by Itsredd** [comment]
Damit sollte die Toolchain vorest Abgedeckt sein. Bitte um review, dass alles passt.

**Comment by xela1601** [comment]
bei packages noch matplotlib zum visualisieren der bilder
ansonsten top. super arbeit
