### ISSUE TITLE
Create Business Model

### ISSUE THREAD

**Issue by Itsredd** [Itsredd/theMillionDollarProject#6]
Es wäre schön wenn wir unser Geschäftskonzept Digital und editierbar haben.
Bitte die [diese Datei](https://github.com/Itsredd/theMillionDollarProject/blob/master/Vorl%C3%A4ufigesGesch%C3%A4ftsmodell.drawio) bearbeiten und updaten!
Datei ist für [Draw.io](Draw.io) ausgelegt!

> „Passwörter sind wie Unterwäsche. Du darfst sie keinen sehen lassen, musst sie regelmäßig wechseln und solltest sie nicht mit Fremden tauschen.“

**Comment by einsStudent** [comment]
Hier findet sich das überarbeitete Geschäftsmodell als png:
https://github.com/Itsredd/theMillionDollarProject/blob/master/Gesch%C3%A4ftsmodell/Gesch%C3%A4ftsmodell_v2.png
und hier editierbar mit draw.io:
https://github.com/Itsredd/theMillionDollarProject/blob/master/Gesch%C3%A4ftsmodell/Vorl%C3%A4ufigesGesch%C3%A4ftsmodell_v2.drawio

**Comment by ChrisMagios** [comment]
canvas ist soweit done.
