### ISSUE TITLE
Personal

### ISSUE THREAD

**Issue by xela1601** [Itsredd/theMillionDollarProject#8]
Es sollte geklärt werden, wieviele Leute wir für welche Postionen benötigen.
Postionen könnten sein:
- Sekretär(in) für Kundenkontakt
- Marketing Spazialisten
- Administrator
- Softwaredeveloper
- Juristen (evtl. Rechtsabteilung)
- Human Resources Leute
bitte noch vervollständigen

**Comment by Gristl** [comment]
mach ich
